### ISSUE TITLE
How to configure "Subscribing to player state changes"

### ISSUE THREAD

**Issue by Leviathan09** [a-i-ks/ioBroker.volumio#1]
Hi,

i've installed your adapter and now trying to get the "Subscribing to player state changes"-option to work but i don't get it.
Can you tell me what and how do i need to configure volumio to push the changes to your adapter.
I'm not very familiar with REST API and that kind of stuff maybe you can help me

**Comment by a-i-ks** [comment]
Hi @Leviathan09,
now it happened again (like with my old version of the Volumio adapter): people want to use the adapter faster than I can get it developed. In fact, the subscription does not work yet. 
I'm still on it right now, then I wanted to officially release the adapter.  I had no experience with TypeScript programming so far, that's why it's going quite slow in my free time. Please be patient for a few more days, then the feature should be available.

**Comment by Leviathan09** [comment]
@a-i-ks no problem at all take your time
just was too enthusiastic after installation of Volumio worked and then googled for an adapter 😄

**Comment by a-i-ks** [comment]
Understandable. There is only my adapter so far. As I said, give me a few more days, then I'll officially release it and you can install it via ioBroker catalog. Then I would be very happy about feedback.

**Comment by a-i-ks** [comment]
The adapter should now work. The subscription mode is now also ready for use. You can install the adapter via GitHub for now. I'll release it via ioBroker in the next few days. Feedback would be great!

**Comment by Leviathan09** [comment]
Installed and it's running fine, all updates done in the webinterface like volume, next song are directly pushed to the adapter.
Only warning i got in the log is the following:
`volumio.0 | 2021-02-04 21:52:59.514 | warn | (27017) State "volumio.0.info.hardware" has no existing object, this might lead to an error in future versions
-- | -- | -- | --`

**Comment by wberger42** [comment]
Also working for me. Thanks a lot for coding this.
Currently there are still some exceptions running through the log and the buttons still don't work. But the playback info works and this is already a great thing for a prerelease adapter. Thanks.

**Comment by a-i-ks** [comment]
Thanks for the feedback. Nice that there are already testers before release. 
@Leviathan09 I have already fixed the problem with the missing state. Was a copy&paste error.
@wberger42 Could you please open separate tickets for the major errors and execeptions? That would be great thanks. Which buttons do not work? I thought that these functions would work stable by now.

**Comment by a-i-ks** [comment]
@Leviathan09 Do the buttons (play,prev,next, ...) work for you?

**Comment by Leviathan09** [comment]
@a-i-ks Yes buttons do work fine for me

**Comment by a-i-ks** [comment]
Perfect. I think I already found @wberger42 problem in the other issue ticket and seems that it's not a problem in the code. I probably need to rework the error handling a bit before release.

**Comment by Leviathan09** [comment]
As "Subscribing" now works fine i close the issue
Thanks @a-i-ks for the work
